### PR TITLE
 #423 lwip arch directories for CIAA's arch

### PR DESCRIPTION
**Pull request by mabeett**
with this change the arch files are just compiled for lpc4337 boards.
There are also error messages in makefiles and cc.h source files
inviting the user to participate

### CODE REVIEW

**Comment by mabeett** [comment]
This patch *is not compatible* with #420 
If #420 is merged the source branch should be updated before merging this orign branch. The patches and script have paths whichs are changed here.

**Comment by mabeett** [comment]
The build and not build has been tested in an ad-hoc branch wich may run succesfuly blinking_lwip example. See mabeett/Firmware@a164f26484b8802af4d63844b188e328dec319ac (423+420+ethernet-funcional-lpceth-arch branch).
The successful build has been downloaded and tested in ciaa_nxp.

**Comment by mcerdeiro** [comment]
Hi Matthias,
do you want me to merge this one or the #420? Or you want to create a third one with all inclusive?
Thanks
Mariano.-

**Comment by mabeett** [comment]
Hi!,
I would preffer first the #422 first (issue #420) since I have commits for adapting this merge to it, not the inverse. =)
This Push request branch has been created considering #422 as a rejected merge.
Cheers,
Mts

**Comment by mcerdeiro** [comment]
done, #422 has been merged, i guess we can close this one without merge?

**Comment by mabeett** [comment]
Yes, there is no problem. I will make a new PR with the updated branches, rebase with the master updates an so on.

**Pull request closed without merging**
